"""empty message

Revision ID: 3aa9d1ba79d2
Revises: af6cb52cb2bd
Create Date: 2018-04-10 17:32:50.631374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa9d1ba79d2'
down_revision = 'af6cb52cb2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('temp_col', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'temp_col')
    # ### end Alembic commands ###
