"""empty message

Revision ID: 9a98ad5c3bd3
Revises: 3aa9d1ba79d2
Create Date: 2018-04-10 17:41:35.002303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a98ad5c3bd3'
down_revision = '3aa9d1ba79d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'temp_col')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('temp_col', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
