"""empty message

Revision ID: f89e254d079f
Revises: 99e40eb679d3
Create Date: 2018-04-04 19:07:33.178862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89e254d079f'
down_revision = '99e40eb679d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hourly_util',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('util_date', sa.Date(), nullable=False),
    sa.Column('util_hour', sa.Integer(), nullable=False),
    sa.Column('util', sa.Float(), nullable=False),
    sa.Column('rev', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('util_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hourly_util')
    # ### end Alembic commands ###
