"""empty message

Revision ID: 27ee3092f453
Revises: f89e254d079f
Create Date: 2018-04-04 19:32:54.799956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ee3092f453'
down_revision = 'f89e254d079f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parkinglot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pl_id', sa.Integer(), nullable=False),
    sa.Column('pl_name', sa.String(length=255), nullable=False),
    sa.Column('pl_address', sa.String(length=255), nullable=False),
    sa.Column('pl_capacity', sa.Integer(), nullable=False),
    sa.Column('pl_default_price', sa.Float(), nullable=False),
    sa.Column('pl_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parkinglot')
    # ### end Alembic commands ###
