"""empty message

Revision ID: 2c69f3ff3419
Revises: 7489f3f18da3
Create Date: 2018-04-09 20:43:13.300094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c69f3ff3419'
down_revision = '7489f3f18da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilization_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pl_id', sa.Integer(), nullable=False),
    sa.Column('util_date', sa.Date(), nullable=False),
    sa.Column('util_per_hour', sa.String(length=175), nullable=False),
    sa.Column('rev_per_hour', sa.String(length=175), nullable=False),
    sa.Column('avg_util', sa.Float(), nullable=False),
    sa.Column('total_rev', sa.Float(), nullable=False),
    sa.Column('isSent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('util_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilization_stage')
    # ### end Alembic commands ###
