"""empty message

Revision ID: 4f2bc6ab89a3
Revises: ef2334b576c1
Create Date: 2018-03-26 00:33:44.925731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2bc6ab89a3'
down_revision = 'ef2334b576c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charge', 'pl_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(u'charge_pl_id_fkey', 'charge', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'charge_pl_id_fkey', 'charge', 'parkinglot', ['pl_id'], ['id'])
    op.alter_column('charge', 'pl_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
