"""empty message

Revision ID: 70b657f2eaa3
Revises: af6cb52cb2bd
Create Date: 2018-04-10 16:43:54.821944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b657f2eaa3'
down_revision = 'af6cb52cb2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('entry_operator_id', sa.String(length=50), nullable=False))
    op.add_column('token', sa.Column('exit_operator_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'exit_operator_id')
    op.drop_column('token', 'entry_operator_id')
    # ### end Alembic commands ###
