"""empty message

Revision ID: af6cb52cb2bd
Revises: 2c69f3ff3419
Create Date: 2018-04-09 20:47:12.460049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6cb52cb2bd'
down_revision = '2c69f3ff3419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilization_stage', sa.Column('is_sent', sa.Boolean(), nullable=False))
    op.drop_column('utilization_stage', 'isSent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilization_stage', sa.Column('isSent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('utilization_stage', 'is_sent')
    # ### end Alembic commands ###
