"""empty message

Revision ID: 2a07e5b62f32
Revises: 8909b6422a2a
Create Date: 2018-03-10 20:07:48.354785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a07e5b62f32'
down_revision = '8909b6422a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authenticated', sa.Boolean(), nullable=True))
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'authenticated')
    # ### end Alembic commands ###
