"""empty message

Revision ID: 4f28a0ba7227
Revises: 8aa9d48a86b7
Create Date: 2018-03-21 12:48:37.056092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f28a0ba7227'
down_revision = '8aa9d48a86b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pl_id', sa.Integer(), nullable=True),
    sa.Column('util_date', sa.Date(), nullable=False),
    sa.Column('util_per_hour', sa.String(length=175), nullable=False),
    sa.Column('rev_per_hour', sa.String(length=175), nullable=False),
    sa.Column('avg_util', sa.Float(), nullable=False),
    sa.Column('total_rev', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pl_id'], ['parkinglot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('util_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilization')
    # ### end Alembic commands ###
