"""empty message

Revision ID: 8aa9d48a86b7
Revises: 781751ac4406
Create Date: 2018-03-21 12:31:36.782289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa9d48a86b7'
down_revision = '781751ac4406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parkinglot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pl_name', sa.String(length=255), nullable=False),
    sa.Column('pl_address', sa.String(length=255), nullable=False),
    sa.Column('pl_capacity', sa.Integer(), nullable=False),
    sa.Column('pl_default_price', sa.Float(), nullable=False),
    sa.Column('pl_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pl_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('utilization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pl_id', sa.Integer(), nullable=False),
    sa.Column('util_date', sa.Date(), nullable=False),
    sa.Column('util_per_hour', sa.String(length=175), nullable=False),
    sa.Column('rev_per_hour', sa.String(length=175), nullable=False),
    sa.Column('avg_util', sa.Float(), nullable=False),
    sa.Column('total_rev', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'pl_id'),
    sa.UniqueConstraint('util_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilization')
    op.drop_table('user')
    op.drop_table('parkinglot')
    # ### end Alembic commands ###
