"""empty message

Revision ID: b7b9d7049899
Revises: f0c9ab697213
Create Date: 2018-04-09 22:50:12.320539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b9d7049899'
down_revision = 'f0c9ab697213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staging_price_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pl_id', sa.Integer(), nullable=False),
    sa.Column('ch_id', sa.Integer(), nullable=False),
    sa.Column('price_snapshot', sa.String(length=2500), nullable=False),
    sa.Column('ch_sent', sa.Boolean(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staging_price_updates')
    # ### end Alembic commands ###
