"""empty message

Revision ID: c1b4c1680f9d
Revises: 4f28a0ba7227
Create Date: 2018-04-07 19:40:20.897820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b4c1680f9d'
down_revision = '4f28a0ba7227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge',
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('pl_id', sa.Integer(), nullable=False),
    sa.Column('price_snapshot', sa.String(length=2500), nullable=False),
    sa.Column('ch_active', sa.Boolean(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('charge_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charge')
    # ### end Alembic commands ###
